language: java
jdk:
  - openjdk8
install: true

addons:
  sonarcloud:
    organization: "bartlomiej-gora"
    token:
      secure: "78f34cd7189b0ebc7027d5271d15be9d6df06ce4"

script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=bartlomiej-gora_RPNLibrary
before_install:
  - wget https://github.com/codacy/codacy-coverage-reporter/releases/download/4.0.3/codacy-coverage-reporter-4.0.3-assembly.jar

after_success:
  - java -jar ~/codacy-coverage-reporter-4.0.3-assembly.jar com.codacy.CodacyCoverageReporter -l Java -r target/site/cobertura/coverage.xml
