language: java
jdk:
  - openjdk8
install: true

script:
 - jdk_switcher use oraclejdk8
 - mvn clean cobertura:cobertura
before_install:
   - wget https://github.com/codacy/codacy-coverage-reporter/releases/download/4.0.3/codacy-coverage-reporter-4.0.3-assembly.jar

after_success:
  - java -jar ~/codacy-coverage-reporter-4.0.3-assembly.jar com.codacy.CodacyCoverageReporter -l Java -r target/site/cobertura/coverage.xml
